version: "3.7"
services:
 postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: dbname
      restart: unless-stopped

networks:
  proxy:
    external: true
